[package]
name = "HexVigil"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
colored = "2.1"
goblin = "0.7" # Per parsing ELF/PE/Mach-O
libc = "0.2"
